FROM golang:1.19-alpine as builder
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download && apk add --no-cache ca-certificates

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/grpc_server/main.go

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/main /main
COPY --from=builder /app/.env /.env

CMD ["/main"]