FROM golang:alpine as builder
RUN apk add --no-cache git
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/grpc_client/main.go
# ------------------------------------------------------
FROM alpine:latest
RUN apk --no-cache add ca-certificates

COPY --from=builder /app/main /main
COPY ./.env ./.env

CMD ["/main"]